# SITE CONFIGURATION
  baseurl: "" # the subpath of your site, e.g. /blog/
  url: "http://timgates2.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
  theme_settings:
  # Meta
  title: Tim Gates Jr.
  avatar: avatar.png
  gravatar: 6904ca3dbe940df5219fbeaf784b75df
  description: "A developer's Portfolio" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Developer/Writer.</h1>
  header_text_feature_image: "sample_feature_img.png"
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: findme@timgatesjr.com
  flickr:
  github: timgates2
  google_plus: 107020662824072811734
  linkedin:  https://www.linkedin.com/in/timgatesjr?trk=nav_responsive_tab_profile_pic
  stack_exchange:  # Full URL
  steam: 76561198087524999

  # Scripts
  google_analytics: "UA-96995309-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # PAGINATION
  paginate: 5
  paginate_path: "blog/page:num"

  # COLLECTIONS
  collections:
  portfolio:
  output: true

  # BUILD SETTINGS
  markdown: kramdown
  sass:
  sass_dir: _sass
  style: :compressed
  
  gems: [jekyll-paginate]